kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build-config
  namespace: is-test  
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'alpine-is:dummy'
  resources:
    limits:
      ephemeral-storage: 100Gi
    requests:
      ephemeral-storage: 30Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:      
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |
      FROM alpine:latest      
      RUN echo "This is a dummy test Dockerfile for BuildConfig" > dummy.message
  runPolicy: Serial
